exclude: [_ignore, CNAME, README.md]

# Dependencies
markdown:          redcarpet
# highlighter:       pygments

# Permalinks
permalink:         pretty

# Setup
title:             Tessera
tagline:           Analyze Large Complex Data with R
url:               http://tessera.io
baseurl:           /
excerpt_separator: <!--more-->

author :
  name : Ryan Hafen
  email : rhafen@gmail.com
  github : hafen
  twitter : hafenstats

authors:
  ryan:
    display_name: Ryan Hafen
    email: rhafen@gmail.com
    # web:
    twitter: hafenstats
    github: hafen

# Custom vars
version:        1.0.0
github:
  repo:         https://github.com/tesseradata/tesseradata.github.io
